# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
<<<<<<< HEAD
# stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
# stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SENDGRID_PASSWORD: exAmplePa$$
SENDGRID_USERNAME: myspecialusername
DEVISE_SECRET_KEY: SEcr3tDeV1seK3Y
AWS_ACCESS_KEY_ID: AKIAIPXZDRFVBFLD5VVA
AWS_SECRET_ACCESS_KEY: KXoM14n1SvDMAgNZ/2TfGEeZemRpDFD7aAND74TP
development:
  AWS_BUCKET: basic-rails-app-development
production:
  AWS_BUCKET: basic-rails-app-production
=======
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
SENDGRID_PASSWORD: your credential here
SENDGRID_USERNAME: your credential here
AWS_ACCESS_KEY_ID: your credential here
AWS_SECRET_ACCESS_KEY: your credential here
development:
  AWS_BUCKET: your credential here
production:
  AWS_BUCKET: your credential here
>>>>>>> checkpoint-45-Pagination
